"""anotehr model change2

Revision ID: 1ea66e846555
Revises: a2bb7fcaec78
Create Date: 2025-06-27 20:32:02.421716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea66e846555'
down_revision = 'a2bb7fcaec78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))
        batch_op.drop_column('isFavorite')
        batch_op.drop_column('isBlocked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isBlocked', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('isFavorite', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_blocked')
        batch_op.drop_column('is_favorite')

    # ### end Alembic commands ###
