"""Set default and non-null for is_favorite and is_blocked

Revision ID: e171c14f75d9
Revises: 1ea66e846555
Create Date: 2025-06-27 20:33:59.242464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e171c14f75d9'
down_revision = '1ea66e846555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
